---
# role: ansible-role-virtinstall
# file: requirements.yml

collections:
  - name: git+https://github.com/jam82/ansible-collection-general.git
    version: main
  - name: community.libvirt

roles: []

# - src: https://github.com/jam82/ansible-role-baseline.git
#   name: baseline
#   version: main
