---
# name: jomrr.virtinstall
# file: meta/requirements.yml

collections:
  - community.libvirt
  - {'name': 'git+https://github.com/jomrr/ansible-collection-general', 'version': 'main'}

roles:
  - {'name': 'git+https://github.com/jomrr/ansible-role-libvirtd', 'version': 'main'}
